# This docker-compose is for development purposes, so user + passwords
# would need to be overwritten during stage/prod builds / deployments

version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mylittletodo

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api:
    build: ./backend
    restart: always
    links:
      - mongo
    ports:
      - 5000:5000

  ui:
    build: ./frontend
    restart: always
    links:
      - api
    ports:
      - 3000:3000
