# This docker-compose is for development purposes, so user + passwords
# would need to be overwritten during stage/prod builds / deployments

version: "3.1"

services:
  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=mylittletodo
      - MONGODB_APPLICATION_USER=mylittletodo
      - MONGODB_APPLICATION_PASS=pass123
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
      - ./mongo_data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   links:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin123

  api:
    build: ./backend
    restart: always
    links:
      - mongo
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://mylittletodo:pass123@mongo:27017/mylittletodo

  ui:
    build: ./frontend
    restart: always
    links:
      - api
    ports:
      - 3000:3000
